teamid_flashscore = {'rma': 'W8mj7MDD', 'bar': 'SKbpVP5K', 'atm': 'jaarqpLQ', 'liv': 'lId4TMwf', 'manu': 'ppjDR086', 'manc': 'Wtn9Stg0', 'che': '4fGZN2oK', 'ars': 'hA1Zm19f', 'tot': 'UDg08Ohm', 'psg': 'CjhkPw0k', 'bay': 'nVp0wiqd', 'bvb': 'nP1i5US1', 'int': 'Iw7eKK25', 'mil': '8Sa8HInO', 'juv': 'C06aJvIB', 'nap': '69Dxbc61', 'est': 'KAtu9Aoa', 'prs': 'KzfvmgGd', 'fra': 'QkGeVG1n', 'ger': 'ptQide1O', 'ita': 'hlKvieGH', 'bel': 'GbB957na', 'eng': 'j9N9ZNFA', 'ned': 'WYintcWb', 'por': 'WvJrjFVN', 'arg': 'f9OppQjp', 'bra': 'I9l9aqLq', 'spa': 'bLyo6mco'}
team_fullname = {
    'rma': 'Real Madrid',
    'bar': 'FC Barcelona',
    'atm': 'Atlético Madrid',
    'liv': 'Liverpool',
    'manu': 'Manchester United',
    'manc': 'Manchester City',
    'che': 'Chelsea',
    'ars': 'Arsenal',
    'tot': 'Tottenham Hotspur',
    'psg': 'Paris Saint-Germain',
    'bay': 'Bayern Munich',
    'bvb': 'Borussia Dortmund',
    'int': 'Inter Milan',
    'mil': 'AC Milan',
    'juv': 'Juventus',
    'nap': 'Napoli',
    'est': 'Esteghlal',
    'prs': 'Persepolis',
    'fra': 'France',
    'ger': 'Germany',
    'ita': 'Italy',
    'bel': 'Belgium',
    'eng': 'England',
    'ned': 'Netherlands',
    'por': 'Portugal',
    'arg': 'Argentina',
    'bra': 'Brazil',
    'spa': 'Spain'
}

team_names_flashscore = {
    'rma': 'real-madrid',
    'bar': 'barcelona',
    'atm': 'atl-madrid',
    'liv': 'liverpool',
    'manu': 'manchester-united',
    'manc': 'manchester-city',
    'che': 'chelsea',
    'ars': 'arsenal',
    'tot': 'tottenham',
    'psg': 'psg',   
    'bay': 'bayern-munich',
    'bvb': 'dortmund',
    'int': 'inter',
    'mil': 'ac-milan',
    'juv': 'juventus',
    'nap': 'napoli',
    'est': 'esteghlal',
    'prs': 'persepolis',
    'fra': 'france',
    'ger': 'germany',
    'ita': 'italy',
    'bel': 'belgium',
    'eng': 'england',
    'ned': 'netherlands',
    'por': 'portugal',
    'arg': 'argentina',
    'bra': 'brazil',
    'spa': 'spain'
}

teamid_sportdb = {
    "rma": "133738",
    "bar": "133739",
    "atm": "133729",
    "liv": "133602",
    "manu": "133612",
    "manc": "133613",
    "che" : "133610",
    "ars": "133604",
    "tot": "133616",
    "psg": "133714",
    "bay": "133664",
    "bvb": "133650",
    "int": "133681",
    "mil": "133667",
    "juv": "133676",
    "nap": "133670",
    "est": "139012",
    "prs": "139013",
    "fra": "133913",
    "ger": "133907",
    "ita": "133910",
    "bel": "134515",
    "eng": "133914",
    "ned": "133905",
    "por": "133908",
    "arg": "134509",
    "bra": "134496",
    "spa": "133909"
}

rooz = {
    0: "شنبه",
    1: "یکشنبه",
    2: "دوشنبه",
    3: "سه‌ شنبه",
    4: "چهارشنبه",
    5: "پنجشنبه",
    6: "جمعه"
}
